version: 0.1.0.{build}
branches:
  only:
    - master
    - dev

skip_tags: true
os: Windows Server 2012
install:
  - ps: .\scripts\init-buildenv.ps1

build_script:
  - cmd: build.cmd
  
test: off

artifacts:
  - path: artifacts
    name: All Artifacts
    type: zip
  - path: artifacts\_WebSites
    name: KLoggy.Web
    type: zip